theme: jekyll-theme-hacker
name: java.design
title: Programming Snippets


baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true

owner : "Adel Zaitri"
year : "2021"

# Site Author
author:
  name             : "Adel Zaitri"